apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: my-python-app-deployment
spec:
  port:
    targetPort: 5000
  to:
    kind: Service
    name: my-python-app-deployment
    weight: 100
  wildcardPolicy: None
